In [ ]:
# used Python 3.13
%pip install numpy==2.4 pandas==3 matplotlib==3.10 datasets==4.5

In [71]:
%pip install chardet

Collecting chardet
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Installing collected packages: chardet
Successfully installed chardet-5.2.0
Note: you may need to restart the kernel to use updated packages.

In [75]:
import chardet
train_df['email'].str.encode('utf-8').apply(chardet.detect)

0        {'encoding': 'ascii', 'confidence': 1.0, 'lang...
1        {'encoding': 'ascii', 'confidence': 1.0, 'lang...
2        {'encoding': 'ascii', 'confidence': 1.0, 'lang...
3        {'encoding': 'ascii', 'confidence': 1.0, 'lang...
4        {'encoding': 'ascii', 'confidence': 1.0, 'lang...
                               ...
33711    {'encoding': 'ascii', 'confidence': 1.0, 'lang...
33712    {'encoding': 'ascii', 'confidence': 1.0, 'lang...
33713    {'encoding': 'ascii', 'confidence': 1.0, 'lang...
33714    {'encoding': 'ascii', 'confidence': 1.0, 'lang...
33715    {'encoding': 'ascii', 'confidence': 1.0, 'lang...
Name: email, Length: 33716, dtype: object

In [ ]:
_.value_counts()

In [ ]:
import ast

import numpy as np
import pandas as pd
from datasets import load_dataset   # loads huggingface datasets & caches them after first download at ~/.cache/huggingface/datasets/

def train_val_split(df: pd.DataFrame, train_split: float = 0.8) -> tuple[pd.DataFrame, pd.DataFrame]:
    mask = np.random.rand(df.shape[0]) < train_split
    train_df = df[mask]
    val_df = df[~mask]
    return train_df, val_df

def clean_text(text: str) -> str:
    """Removes special symbols from text, keeping only alphanumeric """

In [63]:
ds = load_dataset("bvk/ENRON-spam", split="train")

Repo card metadata block was not found. Setting CardData to empty.

In [79]:
# Columns: label (0: not spam, 1: spam) | email (string)
train_df = load_dataset("bvk/ENRON-spam", split="train").to_pandas()[['label', 'email']]
val_df = load_dataset("bvk/SMS-spam", split="train").to_pandas().rename(columns={'data': 'email'})
train_df_org, val_df_org = train_df.copy(), val_df.copy()
train_df_org.to_csv("train.csv", index=False)
val_df_org.to_csv("val.csv", index=False)
# email cells have lists with single string, so parse
train_df['email'] = train_df['email'].apply(lambda s: ast.literal_eval(s)[0])
val_df['email'] = val_df['email'].apply(lambda s: ast.literal_eval(s)[0])
train_df.shape, val_df.shape

Repo card metadata block was not found. Setting CardData to empty.
Repo card metadata block was not found. Setting CardData to empty.

((33716, 2), (5574, 2))

In [67]:
train_df

       label                                              email
0          0       b'Subject: christmas tree farm pictures  \n'
1          0           b'Subject: re : rankings  \nthank you .'
2          0  b'Subject: leadership development pilot  \nsal...
3          0  b"Subject: key dates and impact of upcoming sa...
4          0  b'Subject: key hr issues going forward  \na ) ...
...      ...                                                ...
33711      1  b"Subject: do you wish for a more active sex l...
33712      1  b'Subject: bloow in 5 - 10 times the time  \nl...
33713      1  b'Subject: why didnt you say hi  \nthere is th...
33714      1  b'Subject: dear sir , i am interested in it  \...
33715      1  b'Subject:   \nhtml\nbody\nb\npwhy not take a ...

[33716 rows x 2 columns]

In [50]:
val_df

      label                                              email
0         1  Free entry in 2 a wkly comp to win FA Cup fina...
1         1  "FreeMsg Hey there darling it's been 3 week's ...
2         1  WINNER!! As a valued network customer you have...
3         1  Had your mobile 11 months or more? U R entitle...
4         1  "SIX chances to win CASH! From 100 to 20,000 p...
...     ...                                                ...
5569      0                                       Huh y lei...
5570      0              Will Ã¼ b going to esplanade fr home?
5571      0  "Pity, * was in mood for that. So...any other ...
5572      0  The guy did some bitching but I acted like i'd...
5573      0                         Rofl. Its true to its name

[5574 rows x 2 columns]

In [78]:
'Ã¼ b'.encode('latin-1').decode('utf-8')

'ü b'

In [60]:
''.join(sorted(set(val_df['email'].str.cat())))

' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_abcdefghijklmnopqrstuvwxyz|~¡£¥¦¨©¬º»¼¾ÂÃâãéœˆ˜–‘’“”‰€™'

In [ ]:
import string
'Ã', string.printable

(True,
 '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c')

In [ ]:
lowercase, strip, convert whitespaces to space,