In [5]:
import pandas as pd
train_df = pd.read_excel('knn_imbalanced_dataset_Q2.xlsx', sheet_name='Train')
test_df = pd.read_excel('knn_imbalanced_dataset_Q2.xlsx', sheet_name='Test')

In [6]:
train_df

,Sample_ID,Temperature_C,Pressure_bar,Vibration_mm_s,Current_A,Acoustic_dB,Class
0,S0630,65.86,101.19,1.775,60.77,16.53,Fault
1,S0500,69.05,108.78,0.605,38.71,15.08,Normal
2,S0136,51.40,148.59,0.863,36.94,9.67,Normal
3,S0481,55.77,119.80,1.051,37.81,9.84,Normal
4,S0091,49.48,124.19,1.093,45.38,10.14,Normal
...,...,...,...,...,...,...,...
655,S0072,50.93,122.81,0.841,30.68,9.70,Normal
656,S0107,48.55,108.71,0.733,37.26,6.87,Normal
657,S0271,48.99,126.75,0.606,36.76,13.83,Normal
658,S0436,58.26,114.81,1.091,45.62,11.07,Normal
659,S0103,43.76,116.43,0.815,34.57,11.58,Normal

In [7]:
test_df

,Sample_ID,Temperature_C,Pressure_bar,Vibration_mm_s,Current_A,Acoustic_dB,Class
0,S0174,59.52,98.62,0.816,41.44,13.26,Normal
1,S0179,63.02,118.22,1.104,35.98,15.19,Normal
2,S0183,64.17,95.31,1.922,50.27,15.74,Fault
3,S0133,64.55,123.40,1.093,39.27,11.40,Normal
4,S0191,62.66,87.23,1.906,40.90,14.26,Fault
...,...,...,...,...,...,...,...
205,S0018,51.70,119.72,0.725,27.25,8.98,Normal
206,S0099,48.09,138.58,0.744,38.61,7.05,Normal
207,S0067,52.91,134.29,0.702,34.36,9.66,Normal
208,S0127,52.72,117.55,1.063,48.60,12.99,Normal
209,S0110,40.66,118.87,1.211,39.33,8.38,Normal